run:
  timeout: 5m
  modules-download-mode: readonly
linters:
  enable:
  - dupl
  - exportloopref
  - gochecknoinits
  - goconst
  - gocritic
  - gofmt
  - goimports
  - misspell
  - nolintlint
  - prealloc
  - revive
  - staticcheck
  - testifylint
  - unconvert
  - unparam
  - usestdlibvars
  - whitespace
linters-settings:
issues:
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck
