run:
  timeout: 5m
linters:
  enable:
  - exhaustive
  - exportloopref
  - dupl
  - gochecknoinits
  - goconst
  - gocritic
  - gofmt
  - goimports
  - misspell
  - nolintlint
  - revive
  - unconvert
  - unparam
  - whitespace
linters-settings:
  exhaustive:
    # presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed
    default-signifies-exhaustive: true
issues:
  exclude-rules: []
