run:
  timeout: 5m
  modules-download-mode: readonly
linters:
  enable:
  - exhaustive
  - exportloopref
  - dupl
  - gochecknoinits
  - goconst
  - gocritic
  - gofmt
  - goimports
  - misspell
  - nolintlint
  - prealloc
  - revive
  - staticcheck
  - testifylint
  - unconvert
  - unparam
  - usestdlibvars
  - whitespace
linters-settings:
  exhaustive:
    # presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed
    default-signifies-exhaustive: true
issues:
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck
