apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: relay
spec:
  version: {{ .TagName }}
  homepage: https://github.com/knight42/krelay
  shortDescription: Drop-in "port-forward" replacement with UDP and hostname resolution.
  description: |
    This kubectl plugin is a drop-in replacement for `kubectl port-forward` with some enhanced features:
    * Supports UDP port forwarding
    * Supports simultaneous forwarding of data to multiple targets
    * Forwarding session will not be interfered after performing rolling updates
    * Forwarding data to the given IP or hostname that is accessible within the kubernetes cluster
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/knight42/krelay/releases/download/{{ .TagName }}/kubectl-relay_{{ .TagName }}_darwin-amd64.tar.gz" .TagName }}
    bin: kubectl-relay
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/knight42/krelay/releases/download/{{ .TagName }}/kubectl-relay_{{ .TagName }}_darwin-arm64.tar.gz" .TagName }}
    bin: kubectl-relay
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/knight42/krelay/releases/download/{{ .TagName }}/kubectl-relay_{{ .TagName }}_linux-amd64.tar.gz" .TagName }}
    bin: kubectl-relay
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/knight42/krelay/releases/download/{{ .TagName }}/kubectl-relay_{{ .TagName }}_linux-arm64.tar.gz" .TagName }}
    bin: kubectl-relay
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/knight42/krelay/releases/download/{{ .TagName }}/kubectl-relay_{{ .TagName }}_windows-amd64.tar.gz" .TagName }}
    bin: kubectl-relay.exe
