apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: krelay-system

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - apiservice.yaml

images:
  - name: knight42/krelay-server
    newTag: dev
