name: "Cross Platform Build"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
    tags: ['*']
  schedule:
  - cron: "0 0 * * 1" # At 0:00 on Monday
  workflow_dispatch: {}
concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: read
env:
  GO_VERSION: 1.19
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ format('>= {0}', env.GO_VERSION) }}
        cache: true
    - name: Test
      run: make test
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-pkg-cache: true
        skip-build-cache: true
        only-new-issues: true

  release:
    runs-on: ubuntu-latest
    needs:
    - test
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Build
      run: make -j releases
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: kubectl-relay_v*
        draft: false
        prerelease: false
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.42
